### ISSUE TITLE
hubot-timezone not working

### ISSUE THREAD

**Issue by colossus9** [StPaulThorndale/hubot-rafiki#5]
For the command `rafiki time in Sydney` we are receiving the following error in `./logs/rafiki.log`:

```
[Wed Mar 23 2016 20:04:01 GMT+0000 (UTC)] DEBUG Message 'rafiki time in Chicago' matched regex //./i/; listener.options$
[Wed Mar 23 2016 20:04:01 GMT+0000 (UTC)] DEBUG Executing listener callback for Message 'rafiki time in Chicago'
[Wed Mar 23 2016 20:04:27 GMT+0000 (UTC)] DEBUG Received message { thread_id: 'e3cYCkSuv-3hCR0YzOKaQpl8zk7',
  event: 'message',
  tags: [],
  uuid: 'b8nILgdE-NfiN4AY',
  thread:
   { body: '',
     external_url: null,
     external_comments: 0,
     activities: 0,
     id: 'e3cYCkSuv-3hCR0YzOKaQpl8zk7',
     flow: 'fdc4882f-e3c6-4f05-b505-da32bcbebfb3',
     status: null,
     fields: [],
     actions: [],
     created_at: 1458763498001,
     title: 'rafiki time in Sydney',
     updated_at: '2016-03-23T20:04:58.001Z',
     initial_message: 830,
     internal_comments: 1 },
  id: 830,
  flow: 'fdc4882f-e3c6-4f05-b505-da32bcbebfb3',
  content: 'rafiki time in Sydney',
  sent: 1458763498001,
  app: 'chat',
  created_at: '2016-03-23T20:04:58.001Z',
  attachments: [],
  user: '155666' }
[Wed Mar 23 2016 20:04:27 GMT+0000 (UTC)] DEBUG Message 'rafiki time in Sydney' matched regex //^\s*[@]?rafiki[:,]?\s*($
[Wed Mar 23 2016 20:04:27 GMT+0000 (UTC)] DEBUG Executing listener callback for Message 'rafiki time in Sydney'
[Wed Mar 23 2016 20:04:27 GMT+0000 (UTC)] ERROR TypeError: Cannot call method 'http' of undefined
  at Response.http (/home/ubuntu/hubot-rafiki/node_modules/hubot/src/response.coffee:109:5, <js>:102:25)
  at getTimezoneInfo (/home/ubuntu/hubot-rafiki/scripts/timezone.coffee:37:3, <js>:28:12)
  at sendLocalTime (/home/ubuntu/hubot-rafiki/scripts/timezone.coffee:77:5, <js>:68:14)
  at convertTime (/home/ubuntu/hubot-rafiki/scripts/timezone.coffee:92:5, <js>:89:14)
  at TextListener.callback (/home/ubuntu/hubot-rafiki/scripts/timezone.coffee:116:5, <js>:123:14)
  at executeListener (/home/ubuntu/hubot-rafiki/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
  at allDone (/home/ubuntu/hubot-rafiki/node_modules/hubot/src/middleware.coffee:44:37, <js>:34:16)
  at /home/ubuntu/hubot-rafiki/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/home/ubuntu/hubot-rafiki/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/home/ubuntu/hubot-rafiki/node_modules/async/lib/async.js:268:15)
  at /home/ubuntu/hubot-rafiki/node_modules/hubot/src/middleware.coffee:49:7, <js>:37:22
  at process._tickCallback (node.js:458:13)

[Wed Mar 23 2016 20:04:27 GMT+0000 (UTC)] DEBUG Message 'rafiki time in Sydney' matched regex //./i/; listener.options $
[Wed Mar 23 2016 20:04:27 GMT+0000 (UTC)] DEBUG Executing listener callback for Message 'rafiki time in Sydney'
```

**Comment by colossus9** [comment]
Fixed with workaround in the following commit: https://github.com/StPaulThorndale/hubot-rafiki/commit/b229f98242aa3897e27028e1d2c9af2d8e08dd94
